tls:
  enabled: true
  authClients: true
  existingSecret: "redis-tls-secret"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: "ca.crt"

auth:
  enabled: true
  existingSecret: "redis-password-secret"
  existingSecretPasswordKey: "redis-password"
