global:
  defaultStorageClass: nfs-client

master:
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector:
    node-role.kubernetes.io/worker: worker

replica:
  replicaCount: 1
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  nodeSelector:
    node-role.kubernetes.io/worker: worker

tls:
  enabled: true
  authClients: true
  existingSecret: "redis-tls-secret"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: "ca.crt"

auth:
  enabled: true
  existingSecret: "redis-password-secret"
  existingSecretPasswordKey: "redis-password"
