apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-ca
data:
  tls.crt: |
    {{ .Files.Get .Values.CACertPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-mtls-client-cert
data:
  tls.crt: |
    {{ .Files.Get .Values.mTLSClientCertPath | b64enc }}
  tls.key: |
    {{ .Files.Get .Values.mTLSClientKeyPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-application-yml
data:
  application.yml: |
    {{ .Files.Get .Values.applicationYmlPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-keystore
data:
  keystore.p12: |
    {{ .Files.Get .Values.keystorePath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-truststore
data:
  truststore.p12: |
    {{ .Files.Get .Values.truststorePath | b64enc }}
