apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-ca
data:
  tls.crt: |
    {{ .Files.Get .Values.CACertPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-api-application-properties
data:
  application.properties: |
    {{ .Files.Get .Values.apiPropertiesPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-api-keystore
data:
  keystore.p12: |
    {{ .Files.Get .Values.apiKeystorePath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fosscut.fullname" . }}-truststore
data:
  truststore.p12: |
    {{ .Files.Get .Values.truststorePath | b64enc }}
