apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fosscut.fullname" . }}
rules:
- apiGroups: ["tekton.dev"]
  resources: ["taskruns"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
