controller:
  installPlugins: false
  image:
    registry: "karolstepanienko"
    repository: "fosscut-jenkins-controller"
    tag: "2.492.1-jdk17"
    pullPolicy: "IfNotPresent"

  jenkinsUrlProtocol: https

  httpsKeyStore:
    enable: true
    jenkinsHttpsJksSecretName: "jenkins-keystore-secret"

  admin:
    createSecret: false
    existingSecret: "jenkins-admin-user-secret"

  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    ingressClassName: haproxy
    annotations:
        # use https when connecting to backend services
        haproxy.org/server-ssl: "true"
        # cert used to verify backend services certificate
        haproxy.org/server-ca: "jenkins/fosscut-ca"
    hostName: jenkins.fosscut.com
    tls:
      - secretName: jenkins.fosscut.com-tls-secret
        hosts:
          - jenkins.fosscut.com

agent:
  jenkinsUrl: https://jenkins.jenkins.svc.cluster.local:8080/
  image:
    repository: "karolstepanienko/fosscut-jenkins-inbound-agent"
    tag: "3283.v92c105e0f819-9"

persistence:
  enabled: true
  existingClaim: "fosscut-jenkins-pvc"
