FROM denoland/deno:2.0.5 AS gui-build

WORKDIR /gui
COPY gui/deno.json gui/deno.lock gui/vite.config.js ./
COPY gui/client/src client/src/
COPY gui/client/index.html client/
COPY gui/prod.properties.js client/properties.js
RUN deno run build


FROM ghcr.io/graalvm/native-image-community:21 AS webserver-build

RUN microdnf install findutils which

WORKDIR /app/gui/webserver
COPY gui/webserver/src src
COPY gui/webserver/build.gradle .

WORKDIR /app
COPY gradle gradle
COPY gradlew build.gradle settings.gradle ./

COPY --from=gui-build /gui/client/dist /app/gui/webserver/src/main/resources/static

RUN ./gradlew --no-daemon nativeCompile


FROM alpine:3.21.0 AS final

RUN apk add libc6-compat curl

COPY --from=webserver-build /app/gui/webserver/build/native/nativeCompile/fosscut-gui .

ENTRYPOINT ["/fosscut-gui"]
