FROM gradle:8.11.1-jdk21 AS gradle

WORKDIR /app
COPY gradle gradle
COPY build.gradle .
RUN gradle wrapper


FROM ghcr.io/graalvm/native-image-community:21 AS build

RUN microdnf install findutils

COPY --from=gradle /app/gradle gradle
COPY gradlew build.gradle settings.gradle ./
COPY shared shared
COPY cli cli

RUN ./gradlew --no-daemon cli:nativeCompile


FROM debian:12.8-slim

COPY --from=build /app/cli/build/native/nativeCompile/fosscut .
