server:
  servlet:
    context-path: /api/

spring:
  application:
    name: fosscut-api
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: fosscut-server
          keystore:
            location: file:./../helm/secrets/keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: file:./../helm/secrets/truststore.p12
            password: password
            type: PKCS12
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: password
      ssl:
        bundle: "server"

redis:
  readHost: redis-replicas.redis.svc.cluster.local
  readPort: 6379

airflow:
  hostname: airflow.fosscut.com
  port: 443
  username: fosscut-api-local
  password: password

jenkins:
  hostname: jenkins.fosscut.com
  port: 443
  username: fosscut-api-local
  token: 115bc5d999f2b0e7a8b1b18e38bcbd34ed
