# Recommended enforcing of standardised naming of resources
useStandardNaming: true

# Workloads will run only as separate pods in a k8s cluster
executor: "KubernetesExecutor"

# Allows running DAG task pods in every cluster namespace
multiNamespaceMode: true

# Triggerer is not necessary
triggerer:
  enabled: false

# Monitoring is not necessary
statsd:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/karolstepanienko/fosscut.git
    branch: airflow-dag-example-2
    rev: HEAD
    subPath: "k8s/airflow/dags"

# Necessary for logs to be available through webserver
logs:
  persistence:
    enabled: True

# static webserver secret key ensures that Airflow components only restart when
# necessary
webserverSecretKeySecretName: airflow-webserver-secret-key

# Mount HTTPS secrets
apiServer:
  extraVolumes:
    - name: airflow-webserver-tls-secret
      secret:
        secretName: airflow-webserver-tls-secret
        defaultMode: 0440
        optional: false
  extraVolumeMounts:
    - name: airflow-webserver-tls-secret
      mountPath: "/tls.crt"
      subPath: tls.crt
      readOnly: true
    - name: airflow-webserver-tls-secret
      mountPath: "/tls.key"
      subPath: tls.key
      readOnly: true
  livenessProbe:
    scheme: HTTPS
  readinessProbe:
    scheme: HTTPS
  startupProbe:
    scheme: HTTPS

config:
  # Increase concurrency to allow more tasks to run in parallel
  core:
    dag_concurrency: 25
    max_active_runs_per_dag: 25
  # Enable HTTPS in webserver settings
  webserver:
    web_server_ssl_cert: /tls.crt
    web_server_ssl_key: /tls.key
  # api:
  #   auth_backends: airflow.api.auth.backend.basic_auth

ingress:
  apiServer:
    enabled: true
    ingressClassName: haproxy
    annotations:
        # use https when connecting to backend services
        haproxy.org/server-ssl: "true"
        # cert used to verify backend services certificate
        haproxy.org/server-ca: "fosscut-ca"
    hosts:
      - name: airflow.fosscut.com
        tls:
          enabled: true
          secretName: "airflow.fosscut.com-tls-secret"

# images:
#   pod_template:
#     repository: "karolstepanienko/fosscut-cli-native"
#     tag: "0.0.1"
