resources:
  api:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 2048Mi

tolerations: []
# tolerations:
#   - effect: NoSchedule
#     key: node-role.kubernetes.io/control-plane
