apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tekton.fullname" . }}-cli-redis-connection-secrets
data:
  keystore.p12: |
    {{ .Files.Get .Values.keystorePath | b64enc }}
  truststore.p12: |
    {{ .Files.Get .Values.truststorePath | b64enc }}
  redis-connection-secrets.yaml: |
    {{ .Files.Get .Values.redisConnectionSecretsPath | b64enc }}
