FROM openjdk:21 AS build

RUN microdnf install findutils

COPY gradle gradle
COPY gradlew build.gradle settings.gradle ./
COPY shared shared
COPY api api

RUN ./gradlew --no-daemon api:bootJar


FROM openjdk:21 AS final

COPY --from=build /api/build/libs/api-*.jar fosscut-api.jar

ENTRYPOINT ["java", "-jar", "/fosscut-api.jar"]
