FROM openjdk:21 AS build

RUN microdnf install findutils

COPY gradle gradle
COPY gradlew build.gradle settings.gradle ./
RUN ./gradlew --no-daemon wrapper
COPY src /src

RUN ./gradlew --no-daemon bootJar


FROM openjdk:21 AS final

COPY --from=build /build/libs/fosscut-api-*.jar fosscut-api.jar

ENTRYPOINT java -jar /fosscut-api.jar
